### PR TITLE
fix: replace merge-graphql-schemas with @graphql-tools/merge

### PR DESCRIPTION
**Pull request by adriantodt**
Hi, I tried to fix the issue #142 I've opened previously by following the [migration docs](https://www.graphql-tools.com/docs/migration/migration-from-merge-graphql-schemas) pointed by the [deprecation notice](https://www.npmjs.com/package/merge-graphql-schemas) on the `merge-graphql-schemas` repository.

### CODE REVIEW

**Comment by adriantodt** [comment]
Also excuse me, but I have no idea of what I did wrong.

Can someone explain what's up with the "Semantic Pull Request" check?

**Comment by bboure** [comment]
Thank you @adriantodt 

Semantic Pull Request just checks that the commit follows [this pattern](https://www.conventionalcommits.org/en/v1.0.0/)

This LGTM! Just update the snapshots

**Comment by adriantodt** [comment]
@bboure snapshots updated!

**Comment by bboure** [comment]
Thank you @adriantodt !

**Comment by bboure** [comment]
@all-contributors add @adriantodt for code

**Pull request merged**
