### PR TITLE
feat(simulator): Add support for multiple AppSync APIs

### LINKED ISSUE #90: Cannot use the plugin with multiple AppSync APIs
**Describe the bug**
I have a serverless project with multiple AppSync APIs configured.

E.g.
```
custom:
  appSync:
    - name: api-one
       ...
    - name: api-two
       ...
    - name: api-three
       ...
```

When deploying the stack locally with `sls offline start`, I can only make requests against the first API defined in the list. Trying to make requests on other APIs returns an error stating that the operation doesn't exist.
>Cannot query field \"getField\" on type \"Query\"."

**To Reproduce**
1. Create a project with two or more AppSync APIs.
2. Start it with `sls offline start`.
3. Make a request against any API except the first one.

**Expected behavior**
An endpoint (or host on different ports) exist for each AppSync API

### PR DESCRIPTION
**Pull request by louislatreille**
This adds support for simulating multiple AppSync APIs.

The new code has been tested with a serverless config containing 1 API, and another one containing many APIs. The simulator and hot-reloading still work as expected.

Closes #90

### CODE REVIEW

**Review by bboure — CHANGES_REQUESTED** [review]
Awesome! Thank you! 🚀 

LGTM. I only have one comment:

We have a pretty wide port range available here (at least in the default), I would increment the port number by `10`. It would be easier for humans to calculate mentally.

It also leaves some room for possible future usage.

```
20002
20003
20012
20013 
20022
20023 
```

**Comment by louislatreille** [comment]
Great suggestion! I've made the change.

**Comment by bboure** [comment]
Great, thank you! I'll try to review this and merge over the weekend 🙏

**Review by bboure — APPROVED** [review]
Thank you @louislatreille 
Looks awesome! Great work! 🎉 

I just pushed a fix for the linter and ran prettier on the code.

**Comment by bboure** [comment]
@all-contributors please add @louislatreille for code

**Pull request merged**
