### PR TITLE
BatchInvoke by payload.batchId as an alternative to datasource.name

### PR DESCRIPTION
**Pull request by JimmyHurrah**
In a project I work on we have multiple resolvers using BatchInvoke with the same lambda data source. The current LambdaDataLoader implementation batch by function name which means it tries to batch all the different resolvers using BatchInvoke together no matter what resolver it is using.

My proposed solution adds the option to put batchId in the templates to be able to differentiate them and make the correct batches.

### CODE REVIEW

**Comment by bboure** [comment]
@JimmyHurrah I get your use case. That is something I did not think about. Thank you for raising this issue and opening a PR.

Your solution looks a bit hacky though.
Wouldn't it make more sense to batch the requests by field?
We now get the `fieldName` and `fieldParent` from the payload (`req.payload.info.fieldParent` and `req.payload.info.fieldName`).

We probably could do something like:
```ts
const dataResolverKey = `${this.config.name}-${req.payload.info.fieldParent}-${req.payload.info.fieldName}`
const dataLoader = getBatchDataResolver(dataResolverKey, this.config.invoke);
```

Would your use case be solved by doing so?

**Comment by JimmyHurrah** [comment]
@bboure Yeah it's a bit hacky for sure and your proposed solution looks great! 
However, while inspecting the request I can't see that it has any payload.info.* so I'm not sure what you mean by 
> We now get the fieldName and fieldParent from the payload

I interpret what you say that it would get attached automatically somehow? That would be great since then I could further simplify my mappings.

**Comment by bboure** [comment]
@JimmyHurrah try to rebase from master and reinstall node dependencies. 
This is a new feature in `amplify-cli` that I included in the latest release of this plugin.

**Comment by JimmyHurrah** [comment]
I can't find any of the fields you speak of. 
Im using:
```amplify-appsync-simulator@^1.20.2```
```serverless-appsync-simulator@^0.5.0```
Is it some kind of codegen thing in amplify-cli? all our templates are  written by hand.

**Comment by bboure** [comment]
@JimmyHurrah Could you add a `console.log(req);` [here](https://github.com/bboure/serverless-appsync-simulator/blob/master/src/data-loaders/LambdaDataLoader.js#L18) 

Don't forget to `yarn build --watch`.
You'll also need to rerun the simulator after each change.

**Comment by JimmyHurrah** [comment]
@bboure Ah, I see the misunderstanding now! The fields you are talking about are on the $context going into the template. We don't pass the whole context as payload hence the info field is gone when it arrive as part of the request.

With this knowledge, I might be able to reduce our templates to just 2, One for Invoke and one for BatchInvoke. Today we have the 'fieldName' and 'parentTypeName' hardcoded in each template as 'field' and 'type' 😅 

Im not sure about the fix here in serverless-appsync-simulator though. It might be possible that more people does not pass the context.info into the payload 🤔

**Comment by bboure** [comment]
@JimmyHurrah you are right. I forgot about that "detail" 🙁 

For now, I guess we could use `parentTypeName` and/or `fieldName` if present, and if not, keep doing as it is now.

Here is what my `lambda-request.vtl` file looks like

````vtl
{
    "version": "2018-05-29",
    "operation": "Invoke",
    "payload": {
      "args": $utils.toJson($context.arguments),
      "arguments": $utils.toJson($context.arguments),
      "identity": $utils.toJson($context.identity),
      "source": $utils.toJson($context.source),
      "info": {
        "fieldName": $utils.toJson($context.info.fieldName),
        "parentTypeName": $utils.toJson($context.info.parentTypeName),
        "variables": $utils.toJson($context.info.variables),
        "selectionSetList": $utils.toJson($context.info.selectionSetList),
        "selectionSetGraphQL": $utils.toJson($context.info.selectionSetGraphQL)
      }
    }
}

```

but of course, other might just pass them directly, maybe:

````vtl
{
    "version": "2018-05-29",
    "operation": "Invoke",
    "payload": {
      "args": $utils.toJson($context.arguments),
      "arguments": $utils.toJson($context.arguments),
      "identity": $utils.toJson($context.identity),
      "source": $utils.toJson($context.source),
      "fieldName": $utils.toJson($context.info.fieldName),
      "parentTypeName": $utils.toJson($context.info.parentTypeName)
    }
}

```

So, this is not ideal...


Ideally, we would need to receive the `$context` object within the `load()` function, but that would require some changes in https://github.com/aws-amplify/amplify-cli/tree/master/packages/amplify-appsync-simulator

I guess we could try, and at the same time, implement `BatchInvoke` directly in there (right now it is implemented only here).

**Comment by JimmyHurrah** [comment]
Not sure if and how to reopen this so I put up a new PR https://github.com/bboure/serverless-appsync-simulator/pull/30

**Pull request closed without merging**
